# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/dev/NfcPost

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/dev/NfcPost

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/dev/NfcPost/CMakeFiles /home/pi/dev/NfcPost/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/dev/NfcPost/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NfcPost

# Build rule for target.
NfcPost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NfcPost
.PHONY : NfcPost

# fast build rule for target.
NfcPost/fast:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/build
.PHONY : NfcPost/fast

BlinkOk.o: BlinkOk.c.o
.PHONY : BlinkOk.o

# target to build an object file
BlinkOk.c.o:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/BlinkOk.c.o
.PHONY : BlinkOk.c.o

BlinkOk.i: BlinkOk.c.i
.PHONY : BlinkOk.i

# target to preprocess a source file
BlinkOk.c.i:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/BlinkOk.c.i
.PHONY : BlinkOk.c.i

BlinkOk.s: BlinkOk.c.s
.PHONY : BlinkOk.s

# target to generate assembly for a file
BlinkOk.c.s:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/BlinkOk.c.s
.PHONY : BlinkOk.c.s

BuzzIt.o: BuzzIt.c.o
.PHONY : BuzzIt.o

# target to build an object file
BuzzIt.c.o:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/BuzzIt.c.o
.PHONY : BuzzIt.c.o

BuzzIt.i: BuzzIt.c.i
.PHONY : BuzzIt.i

# target to preprocess a source file
BuzzIt.c.i:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/BuzzIt.c.i
.PHONY : BuzzIt.c.i

BuzzIt.s: BuzzIt.c.s
.PHONY : BuzzIt.s

# target to generate assembly for a file
BuzzIt.c.s:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/BuzzIt.c.s
.PHONY : BuzzIt.c.s

GetJsonNow.o: GetJsonNow.c.o
.PHONY : GetJsonNow.o

# target to build an object file
GetJsonNow.c.o:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/GetJsonNow.c.o
.PHONY : GetJsonNow.c.o

GetJsonNow.i: GetJsonNow.c.i
.PHONY : GetJsonNow.i

# target to preprocess a source file
GetJsonNow.c.i:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/GetJsonNow.c.i
.PHONY : GetJsonNow.c.i

GetJsonNow.s: GetJsonNow.c.s
.PHONY : GetJsonNow.s

# target to generate assembly for a file
GetJsonNow.c.s:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/GetJsonNow.c.s
.PHONY : GetJsonNow.c.s

GetSerial.o: GetSerial.c.o
.PHONY : GetSerial.o

# target to build an object file
GetSerial.c.o:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/GetSerial.c.o
.PHONY : GetSerial.c.o

GetSerial.i: GetSerial.c.i
.PHONY : GetSerial.i

# target to preprocess a source file
GetSerial.c.i:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/GetSerial.c.i
.PHONY : GetSerial.c.i

GetSerial.s: GetSerial.c.s
.PHONY : GetSerial.s

# target to generate assembly for a file
GetSerial.c.s:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/GetSerial.c.s
.PHONY : GetSerial.c.s

LogTap.o: LogTap.c.o
.PHONY : LogTap.o

# target to build an object file
LogTap.c.o:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/LogTap.c.o
.PHONY : LogTap.c.o

LogTap.i: LogTap.c.i
.PHONY : LogTap.i

# target to preprocess a source file
LogTap.c.i:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/LogTap.c.i
.PHONY : LogTap.c.i

LogTap.s: LogTap.c.s
.PHONY : LogTap.s

# target to generate assembly for a file
LogTap.c.s:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/LogTap.c.s
.PHONY : LogTap.c.s

Mifare.o: Mifare.c.o
.PHONY : Mifare.o

# target to build an object file
Mifare.c.o:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/Mifare.c.o
.PHONY : Mifare.c.o

Mifare.i: Mifare.c.i
.PHONY : Mifare.i

# target to preprocess a source file
Mifare.c.i:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/Mifare.c.i
.PHONY : Mifare.c.i

Mifare.s: Mifare.c.s
.PHONY : Mifare.s

# target to generate assembly for a file
Mifare.c.s:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/Mifare.c.s
.PHONY : Mifare.c.s

TapPost.o: TapPost.c.o
.PHONY : TapPost.o

# target to build an object file
TapPost.c.o:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/TapPost.c.o
.PHONY : TapPost.c.o

TapPost.i: TapPost.c.i
.PHONY : TapPost.i

# target to preprocess a source file
TapPost.c.i:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/TapPost.c.i
.PHONY : TapPost.c.i

TapPost.s: TapPost.c.s
.PHONY : TapPost.s

# target to generate assembly for a file
TapPost.c.s:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/TapPost.c.s
.PHONY : TapPost.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/main.c.s
.PHONY : main.c.s

timeStrNow.o: timeStrNow.c.o
.PHONY : timeStrNow.o

# target to build an object file
timeStrNow.c.o:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/timeStrNow.c.o
.PHONY : timeStrNow.c.o

timeStrNow.i: timeStrNow.c.i
.PHONY : timeStrNow.i

# target to preprocess a source file
timeStrNow.c.i:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/timeStrNow.c.i
.PHONY : timeStrNow.c.i

timeStrNow.s: timeStrNow.c.s
.PHONY : timeStrNow.s

# target to generate assembly for a file
timeStrNow.c.s:
	$(MAKE) -f CMakeFiles/NfcPost.dir/build.make CMakeFiles/NfcPost.dir/timeStrNow.c.s
.PHONY : timeStrNow.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... NfcPost"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BlinkOk.o"
	@echo "... BlinkOk.i"
	@echo "... BlinkOk.s"
	@echo "... BuzzIt.o"
	@echo "... BuzzIt.i"
	@echo "... BuzzIt.s"
	@echo "... GetJsonNow.o"
	@echo "... GetJsonNow.i"
	@echo "... GetJsonNow.s"
	@echo "... GetSerial.o"
	@echo "... GetSerial.i"
	@echo "... GetSerial.s"
	@echo "... LogTap.o"
	@echo "... LogTap.i"
	@echo "... LogTap.s"
	@echo "... Mifare.o"
	@echo "... Mifare.i"
	@echo "... Mifare.s"
	@echo "... TapPost.o"
	@echo "... TapPost.i"
	@echo "... TapPost.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... timeStrNow.o"
	@echo "... timeStrNow.i"
	@echo "... timeStrNow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

